#cloud-config
chpasswd:
  expire: false
  list: |
    root:${bigiq_admin_password}
    admin:${bigiq_admin_password}
bigiq_dhcpv4_tmm:
  enabled: true
  rd_enabled: false
  dhcp_timeout: 120
  license_key: ${license_basekey}
  node_type: cm
  phone_home_url: ${phone_home_url}
  phone_home_url_verify_tls: false
  phone_home_url_metadata:
    template_source: ${template_source}
    template_version: ${template_version}
    zone: ${zone}
    vpc: ${vpc}
    app_id: ${app_id}
bigiq_playbooks:
  enabled: True
  playbooks:
    - name: license_regkey_pool
      vars:
        license_pool_name: ${license_pool_name}
        license_offerings:
          - ${license_offerings_1}
          - ${license_offerings_2}
          - ${license_offerings_3}
          - ${license_offerings_4}
          - ${license_offerings_5}
          - ${license_offerings_6}
          - ${license_offerings_7}
          - ${license_offerings_8}
          - ${license_offerings_9}
          - ${license_offerings_10}
